<?php
return [
    "StatusSuccess" => "The operation was successful.",
    "StatusFailure" => "Operation failed. Please try again.",
    "MissingParameters" => "Missing parameters. Please check:",
    "EnterAccount" => "Please enter the account.",
    "EnterPassword" => "Please enter the password.",
    "LogIn" => "Log in",
    "AccountOrPasswordNotExists" => "The account or password does not exist.",
    "AccountOrPasswordIncorrect" => "The account or password is incorrect",
    "KeyUpdateFailed" => "The key update failed. Please try again",
    "AdministratorManagementCenter" => "Administrator Management Center",
    "EnterWebsiteName" => "Please enter the account.",
    "ConfigurationNotChanged" => "The configuration information has not changed. Please check",
    "YourLocation" => "Your Location",
    "SystemMainInterface" => "System Main Interface",
    "GlobalSettings" => "Global Settings",
    "BasicSettings" => "Basic Settings",
    "WebsiteName" => "Website Name",
    "PleaseEnterWebsiteName" => "Please enter the website name",
    "RequiredFields" => "Required fields",
    "WebsiteKeywords" => "Website Keywords",
    "PleaseEnterWebsiteKeywords" => "Please enter website keywords",
    "PleaseEnterWebsiteKeywordsDesc" => "Not required field, search engine optimization, please fill in industry keywords, usage, number separation",
    "WebsiteIntroduction" => "Website Introduction",
    "WebsiteIntroductionDesc" => "Not required field, search engine optimization, please fill in the website introduction",
    "SiteStatus" => "Site Status",
    "On" => "On",
    "Off" => "Off",
    "OK" => "OK",
    "CurrentLanguage" => "Current Language",
];
?>